---
global:
  tolerations:
    - key: "eks.k8s.io/instance"
      operator: "Equal"
      value: "tixora-api"
      effect: "NoSchedule"

replicaCount: 1
revisionHistoryLimit: 10

image:
  repository: ghcr.io/external-secrets/external-secrets
  pullPolicy: IfNotPresent

# Manually Install CRDs with below command:
# kubectl apply -f https://raw.githubusercontent.com/external-secrets/external-secrets/main/deploy/crds/bundle.yaml --server-side
installCRDs: false
crds:
  createClusterExternalSecret: true
  createClusterSecretStore: true
  createSecretStore: true
  createClusterGenerator: true
  createClusterPushSecret: true
  createPushSecret: true
  annotations: {}
  conversion:
    enabled: false
  unsafeServeV1Beta1: false

  log:
    level: info
    timeEncoding: epoch