apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.defaults.labels }}-stable
  {{- if .Values.defaults.namespace.enabled }}
  namespace: {{ .Values.defaults.namespace.name }}
  {{- end }}
  annotations:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.defaults.namespace.name }}
spec:
  type: {{ .Values.service.stable.type }}
  {{- with .Values.service.stable.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.stable.externalTrafficPolicy }}
  {{- end }}
  selector:
    app: {{ .Values.defaults.labels }}
  ports:
    - name: {{ .Values.service.ports.https.name }}
      protocol: {{ .Values.service.ports.https.protocol }}
      port: {{ .Values.service.ports.https.port }}
      targetPort: {{ .Values.service.ports.https.targetPort }}
      {{- if and (or (eq .Values.service.stable.type "NodePort") (eq .Values.service.stable.type "LoadBalancer")) .Values.service.stable.nodePort }}
      nodePort: {{ .Values.service.stable.nodePort }}
      {{- end }}
      
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.defaults.labels }}-canary
  {{- if .Values.defaults.namespace.enabled }}
  namespace: {{ .Values.defaults.namespace.name }}
  {{- end }}
  annotations:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.defaults.namespace.name }}
spec:
  type: {{ .Values.service.canary.type }}
  selector:
    app: {{ .Values.defaults.labels }}
  ports:
    - name: {{ .Values.service.ports.https.name }}
      protocol: {{ .Values.service.ports.https.protocol }}
      port: {{ .Values.service.ports.https.port }}
      targetPort: {{ .Values.service.ports.https.targetPort }}
