apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.defaults.labels }}
  {{- if .Values.defaults.namespace.enabled }}
  namespace: {{ .Values.defaults.namespace.name }}
  {{- end }}
  annotations:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    meta.helm.sh/release-name: {{ .Release.Name }}
spec:
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- else}}
  type: {{ .Values.service.type }}
  {{- end }}
  selector:
    app: {{ .Values.defaults.labels }}
  ports:
    - name: {{ .Values.service.ports.https.name }}
      protocol: {{ .Values.service.ports.https.protocol }}
      port: {{ .Values.service.ports.https.port }}
      targetPort: {{ .Values.service.ports.https.targetPort }}