{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  {{- if .Values.defaults.namespace.enabled }}
  namespace: {{ .Values.defaults.namespace.name }}
  {{- end }}
  annotations:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.defaults.namespace.name}}
type: {{ .Values.secret.type }}
data:
  .dockercfg: {{ .Values.secret.data }}
{{- end }}
